@ echo off
title EXTRACCION DE TRAZAS INTERSIG
color F3
echo ********************************************************************************
echo *                         Descargar trazas Intersig                            *
echo ********************************************************************************
echo .................,..... ........................................................
echo ..?NDNNNNNND7...8D.....ON$.......Z8?.......OO.........?NDDNNDDD....ZNNDDDDD?....
echo ......,8~.......DN.....O8Z......DD$O..,....8N.........?D~.....,.,.78............
echo .......8+.......DD8DDD888Z...,.8N..OD,.....8N.........?O8888,.....IDDN8DDDN,....
echo ......,8+.......DDII???ODZ....~8~++.88,....8N.........?OZZ$Z,......Z88888ONO....
echo .......8+.......DD.....ODO....87.?I,,8O....88.........?8,..............,.=D8....
echo .......7:.......8D,....Z8$..+OO......IO8,..ODNNNNDO...+DNNDDDDD...ODDNNNDNO.....
echo ................................................................................
echo ...................___________________ ___________________......................
echo ...................^|                 ^| ^|                 ^|......................
echo ...................^|       __        ^| ^|       __        ^|......................
echo ...................^|      (__)       ^| ^|      (__)       ^|......................
echo ...................^|                 ^| ^|                 ^|......................
echo ...................^|      ©          ^| ^|      ©          ^|......................
echo ...................^|                 ^| ^|                 ^|......................
echo ...................^|      oooo       ^| ^|      oooo       ^|......................
echo ...................^|                 ^| ^|                 ^|......................
echo ...................^|       _____     ^| ^|       _____     ^|......................
echo ...................^|      ^|     ^|    ^| ^|      ^|     ^|    ^|......................
echo ...................^|      ^| \^|/ ^|    ^| ^|      ^| \^|/ ^|    ^|......................
echo ...................^|      ^| /^|\ ^|    ^| ^|      ^| /^|\ ^|    ^|......................
echo ...................^|      ^|_____^|    ^| ^|      ^|_____^|    ^|......................
echo ...................^|                 ^| ^|                 ^|......................
echo ...................^|         o       ^| ^|         o       ^|......................
echo ...................^|        /^|       ^| ^|        /^|       ^|......................
echo ...................^|       ^| ^|       ^| ^|       ^| ^|       ^|......................
echo ...................^|        \^|       ^| ^|        \^|       ^|......................
echo ...................^|         o       ^| ^|         o       ^|......................
echo ...................^|                 ^| ^|                 ^|......................
echo ...................^|_________________^| ^|_________________^|......................
echo ................................................................................
echo.
echo                                                  Hecho por Juan Carlos Benayas ©
ping -n 8 127.0.0.1 > null
cls
color F8
:configuracion
echo Introduzca la direccion IP del EC o IM
set /p ip=
echo Introduzca una direccion libre del mismo rango (p.ej: XXX.XXX.XXX.200)
set /p ip_conf=
netsh interface ip set address "Local Area Connection" static %ip_conf% 255.255.255.0
ping -n 1 %ip% >null || echo IP incorrecta o cable de red desconectado && goto :configuracion 
echo Introduzca el nombre del EC o IM ( ejemplo: EC1.1 o IM1.1)
set /p nomec=
mkdir c:\TRAZAS\%nomec%
mkdir c:\TRAZAS\%nomec%\olt
mkdir c:\TRAZAS\%nomec%\var\log
mkdir c:\TRAZAS\%nomec%\tmp
mkdir c:\TRAZAS\%nomec%\proc
echo root> c:\TRAZAS\temp.txt
echo bin >> c:\TRAZAS\temp.txt
echo hash >> c:\TRAZAS\temp.txt
echo prompt >> c:\TRAZAS\temp.txt
echo lcd %nomec%/olt >> c:\TRAZAS\temp.txt
echo mget /olt/* >> c:\TRAZAS\temp.txt
echo lcd ../var/log >> c:\TRAZAS\temp.txt
echo mget /var/log/* >> c:\TRAZAS\temp.txt
echo lcd ../../tmp >> c:\TRAZAS\temp.txt
echo mget /tmp/* >> c:\TRAZAS\temp.txt
echo lcd ../proc >> c:\TRAZAS\temp.txt
echo mget /proc/syslog >> c:\TRAZAS\temp.txt
echo bye >> c:\TRAZAS\temp.txt
ftp -s:c:\TRAZAS\temp.txt %ip%
del c:\TRAZAS\temp.txt
explorer c:\TRAZAS\%nomec%
msg * Trazas extraidas en c:\TRAZAS\%nomec%
exit
